export enum UserRole {
  SUPER_ADMIN = "SUPER_ADMIN",
  PLATFORM_ADMIN = "PLATFORM_ADMIN",
  INSTITUTION_ADMIN = "INSTITUTION_ADMIN",
  INSTITUTION_COORDINATOR = "INSTITUTION_COORDINATOR",
  FACULTY = "FACULTY",
  STUDENT = "STUDENT",
}